version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management port
    environment:
      RABBITMQ_DEFAULT_USER: baloghlan  # Change this
      RABBITMQ_DEFAULT_PASS: baloghlan1234  # Change this
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data

volumes:
  rabbitmq_data:
    driver: local
